include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - avoid_print
    - use_build_context_synchronously
    - library_private_types_in_public_api
    - sort_child_properties_last
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_this
    - use_key_in_widget_constructors
